name: Build Installers & Upload To Release

on:
  release:
    types: [ created ]

jobs:
  build-linux-installer:
    name: Build Installer on Linux
    runs-on: ubuntu-latest
    steps:

      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          mvn -v
          mvn clean package
          jpackage --input target/ --dest target/ --name Yatran --app-version 1.0.0 --description 'Typing tutor for children that allows improving typing words speed in a fun way' --icon src/main/resources/images/icon.png --main-jar Yatran-1.0.0-jar-with-dependencies.jar --main-class ua.com.yatran.Yatran --type deb --linux-shortcut
      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer to temp
        uses: actions/upload-artifact@v3
        with:
          path: ./consoleapp/build/target/Yatran-1.0.0.deb
          name: linux-installer
          retention-days: 1


  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:

      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          mvn -v
          mvn clean package
          jpackage --input target/ --dest target/ --name Yatran --app-version 1.0.0 --description 'Typing tutor for children that allows improving typing words speed in a fun way' --icon src/main/resources/images/icon.ico --main-jar Yatran-1.0.0-jar-with-dependencies.jar --main-class ua.com.yatran.Yatran --type msi --win-dir-chooser --win-menu --win-per-user-install --win-shortcut
      # SAVE INSTALLER
      - id: upload-installer to temp
        name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: ./consoleapp/build/distributions/target/Yatran-1.0.0.msi
          name: windows-installer
          retention-days: 1


  build-macos-installer:
    name: Build Installer on MacOS
    runs-on: macos-latest
    steps:

      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      # BUILD FOR DISTRIBUTION
      - id: build
        name: Build distribution
        run: |
          mvn -v
          mvn clean package
          jpackage --input target/ --dest target/ --name Yatran --app-version 1.0.0 --description 'Typing tutor for children that allows improving typing words speed in a fun way' --icon src/main/resources/images/icon.icns --main-jar Yatran-1.0.0-jar-with-dependencies.jar --main-class ua.com.yatran.Yatran --type pkg
      # SAVE INSTALLER
      - id: upload-installer
        name: Upload installer to temp
        uses: actions/upload-artifact@v3
        with:
          path: ./consoleapp/build/distributions/target/Yatran-1.0.0.pkg
          name: macos-installer
          retention-days: 1


  upload-to-release:
    name: Upload Installers To Release
    runs-on: ubuntu-latest
    needs: [ build-linux-installer, build-windows-installer, build-macos-installer ]
    steps:

      # DOWNLOAD INSTALLERS
      - id: download-linux-installer
        name: Download Linux installer
        uses: actions/download-artifact@v3
        with:
          name: linux-installer

      - id: download-windows-installer
        name: Download Windows installer
        uses: actions/download-artifact@v3
        with:
          name: windows-installer

      - id: download-macos-installer
        name: Download MacOS installer
        uses: actions/download-artifact@v3
        with:
          name: macos-installer

      # UPLOAD INSTALLERS TO THE LATEST RELEASE
      - id: release-linux-installer
        name: Upload Linux installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: Yatran-1.0.0.deb
          asset_content_type: application/x-binary
      - id: release-windows-installer
        name: Upload Windows installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: Yatran-1.0.0.msi
          asset_content_type: application/x-binary
      - id: release-macos-installer
        name: Upload MacOS installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: Yatran-1.0.0.pkg
          asset_content_type: application/x-binary